# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shion/Dropbox/class/study/implementation/LDA_cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shion/Dropbox/class/study/implementation/LDA_cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shion/Dropbox/class/study/implementation/LDA_cmake/CMakeFiles /home/shion/Dropbox/class/study/implementation/LDA_cmake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shion/Dropbox/class/study/implementation/LDA_cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LDA

# Build rule for target.
LDA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LDA
.PHONY : LDA

# fast build rule for target.
LDA/fast:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/build
.PHONY : LDA/fast

#=============================================================================
# Target rules for targets named ATM

# Build rule for target.
ATM: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ATM
.PHONY : ATM

# fast build rule for target.
ATM/fast:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/build
.PHONY : ATM/fast

#=============================================================================
# Target rules for targets named LDAWBIC

# Build rule for target.
LDAWBIC: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LDAWBIC
.PHONY : LDAWBIC

# fast build rule for target.
LDAWBIC/fast:
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/build
.PHONY : LDAWBIC/fast

src/ATM.o: src/ATM.cpp.o

.PHONY : src/ATM.o

# target to build an object file
src/ATM.cpp.o:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/ATM.cpp.o
.PHONY : src/ATM.cpp.o

src/ATM.i: src/ATM.cpp.i

.PHONY : src/ATM.i

# target to preprocess a source file
src/ATM.cpp.i:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/ATM.cpp.i
.PHONY : src/ATM.cpp.i

src/ATM.s: src/ATM.cpp.s

.PHONY : src/ATM.s

# target to generate assembly for a file
src/ATM.cpp.s:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/ATM.cpp.s
.PHONY : src/ATM.cpp.s

src/AuthorFileParser.o: src/AuthorFileParser.cpp.o

.PHONY : src/AuthorFileParser.o

# target to build an object file
src/AuthorFileParser.cpp.o:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/AuthorFileParser.cpp.o
.PHONY : src/AuthorFileParser.cpp.o

src/AuthorFileParser.i: src/AuthorFileParser.cpp.i

.PHONY : src/AuthorFileParser.i

# target to preprocess a source file
src/AuthorFileParser.cpp.i:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/AuthorFileParser.cpp.i
.PHONY : src/AuthorFileParser.cpp.i

src/AuthorFileParser.s: src/AuthorFileParser.cpp.s

.PHONY : src/AuthorFileParser.s

# target to generate assembly for a file
src/AuthorFileParser.cpp.s:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/AuthorFileParser.cpp.s
.PHONY : src/AuthorFileParser.cpp.s

src/BOWFileParser.o: src/BOWFileParser.cpp.o

.PHONY : src/BOWFileParser.o

# target to build an object file
src/BOWFileParser.cpp.o:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/BOWFileParser.cpp.o
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/BOWFileParser.cpp.o
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/src/BOWFileParser.cpp.o
.PHONY : src/BOWFileParser.cpp.o

src/BOWFileParser.i: src/BOWFileParser.cpp.i

.PHONY : src/BOWFileParser.i

# target to preprocess a source file
src/BOWFileParser.cpp.i:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/BOWFileParser.cpp.i
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/BOWFileParser.cpp.i
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/src/BOWFileParser.cpp.i
.PHONY : src/BOWFileParser.cpp.i

src/BOWFileParser.s: src/BOWFileParser.cpp.s

.PHONY : src/BOWFileParser.s

# target to generate assembly for a file
src/BOWFileParser.cpp.s:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/BOWFileParser.cpp.s
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/BOWFileParser.cpp.s
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/src/BOWFileParser.cpp.s
.PHONY : src/BOWFileParser.cpp.s

src/CollapsedGibbsSamplerFromATM.o: src/CollapsedGibbsSamplerFromATM.cpp.o

.PHONY : src/CollapsedGibbsSamplerFromATM.o

# target to build an object file
src/CollapsedGibbsSamplerFromATM.cpp.o:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/CollapsedGibbsSamplerFromATM.cpp.o
.PHONY : src/CollapsedGibbsSamplerFromATM.cpp.o

src/CollapsedGibbsSamplerFromATM.i: src/CollapsedGibbsSamplerFromATM.cpp.i

.PHONY : src/CollapsedGibbsSamplerFromATM.i

# target to preprocess a source file
src/CollapsedGibbsSamplerFromATM.cpp.i:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/CollapsedGibbsSamplerFromATM.cpp.i
.PHONY : src/CollapsedGibbsSamplerFromATM.cpp.i

src/CollapsedGibbsSamplerFromATM.s: src/CollapsedGibbsSamplerFromATM.cpp.s

.PHONY : src/CollapsedGibbsSamplerFromATM.s

# target to generate assembly for a file
src/CollapsedGibbsSamplerFromATM.cpp.s:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/CollapsedGibbsSamplerFromATM.cpp.s
.PHONY : src/CollapsedGibbsSamplerFromATM.cpp.s

src/CollapsedGibbsSamplerFromLDA.o: src/CollapsedGibbsSamplerFromLDA.cpp.o

.PHONY : src/CollapsedGibbsSamplerFromLDA.o

# target to build an object file
src/CollapsedGibbsSamplerFromLDA.cpp.o:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/CollapsedGibbsSamplerFromLDA.cpp.o
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/CollapsedGibbsSamplerFromLDA.cpp.o
.PHONY : src/CollapsedGibbsSamplerFromLDA.cpp.o

src/CollapsedGibbsSamplerFromLDA.i: src/CollapsedGibbsSamplerFromLDA.cpp.i

.PHONY : src/CollapsedGibbsSamplerFromLDA.i

# target to preprocess a source file
src/CollapsedGibbsSamplerFromLDA.cpp.i:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/CollapsedGibbsSamplerFromLDA.cpp.i
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/CollapsedGibbsSamplerFromLDA.cpp.i
.PHONY : src/CollapsedGibbsSamplerFromLDA.cpp.i

src/CollapsedGibbsSamplerFromLDA.s: src/CollapsedGibbsSamplerFromLDA.cpp.s

.PHONY : src/CollapsedGibbsSamplerFromLDA.s

# target to generate assembly for a file
src/CollapsedGibbsSamplerFromLDA.cpp.s:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/CollapsedGibbsSamplerFromLDA.cpp.s
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/CollapsedGibbsSamplerFromLDA.cpp.s
.PHONY : src/CollapsedGibbsSamplerFromLDA.cpp.s

src/GibbsSamplerFromATM.o: src/GibbsSamplerFromATM.cpp.o

.PHONY : src/GibbsSamplerFromATM.o

# target to build an object file
src/GibbsSamplerFromATM.cpp.o:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/GibbsSamplerFromATM.cpp.o
.PHONY : src/GibbsSamplerFromATM.cpp.o

src/GibbsSamplerFromATM.i: src/GibbsSamplerFromATM.cpp.i

.PHONY : src/GibbsSamplerFromATM.i

# target to preprocess a source file
src/GibbsSamplerFromATM.cpp.i:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/GibbsSamplerFromATM.cpp.i
.PHONY : src/GibbsSamplerFromATM.cpp.i

src/GibbsSamplerFromATM.s: src/GibbsSamplerFromATM.cpp.s

.PHONY : src/GibbsSamplerFromATM.s

# target to generate assembly for a file
src/GibbsSamplerFromATM.cpp.s:
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/GibbsSamplerFromATM.cpp.s
.PHONY : src/GibbsSamplerFromATM.cpp.s

src/GibbsSamplerFromLDA.o: src/GibbsSamplerFromLDA.cpp.o

.PHONY : src/GibbsSamplerFromLDA.o

# target to build an object file
src/GibbsSamplerFromLDA.cpp.o:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/GibbsSamplerFromLDA.cpp.o
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/GibbsSamplerFromLDA.cpp.o
.PHONY : src/GibbsSamplerFromLDA.cpp.o

src/GibbsSamplerFromLDA.i: src/GibbsSamplerFromLDA.cpp.i

.PHONY : src/GibbsSamplerFromLDA.i

# target to preprocess a source file
src/GibbsSamplerFromLDA.cpp.i:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/GibbsSamplerFromLDA.cpp.i
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/GibbsSamplerFromLDA.cpp.i
.PHONY : src/GibbsSamplerFromLDA.cpp.i

src/GibbsSamplerFromLDA.s: src/GibbsSamplerFromLDA.cpp.s

.PHONY : src/GibbsSamplerFromLDA.s

# target to generate assembly for a file
src/GibbsSamplerFromLDA.cpp.s:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/GibbsSamplerFromLDA.cpp.s
	$(MAKE) -f CMakeFiles/ATM.dir/build.make CMakeFiles/ATM.dir/src/GibbsSamplerFromLDA.cpp.s
.PHONY : src/GibbsSamplerFromLDA.cpp.s

src/LDA.o: src/LDA.cpp.o

.PHONY : src/LDA.o

# target to build an object file
src/LDA.cpp.o:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/LDA.cpp.o
.PHONY : src/LDA.cpp.o

src/LDA.i: src/LDA.cpp.i

.PHONY : src/LDA.i

# target to preprocess a source file
src/LDA.cpp.i:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/LDA.cpp.i
.PHONY : src/LDA.cpp.i

src/LDA.s: src/LDA.cpp.s

.PHONY : src/LDA.s

# target to generate assembly for a file
src/LDA.cpp.s:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/LDA.cpp.s
.PHONY : src/LDA.cpp.s

src/LDAWBIC.o: src/LDAWBIC.cpp.o

.PHONY : src/LDAWBIC.o

# target to build an object file
src/LDAWBIC.cpp.o:
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/src/LDAWBIC.cpp.o
.PHONY : src/LDAWBIC.cpp.o

src/LDAWBIC.i: src/LDAWBIC.cpp.i

.PHONY : src/LDAWBIC.i

# target to preprocess a source file
src/LDAWBIC.cpp.i:
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/src/LDAWBIC.cpp.i
.PHONY : src/LDAWBIC.cpp.i

src/LDAWBIC.s: src/LDAWBIC.cpp.s

.PHONY : src/LDAWBIC.s

# target to generate assembly for a file
src/LDAWBIC.cpp.s:
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/src/LDAWBIC.cpp.s
.PHONY : src/LDAWBIC.cpp.s

src/LDAWBICMetropolisSampler.o: src/LDAWBICMetropolisSampler.cpp.o

.PHONY : src/LDAWBICMetropolisSampler.o

# target to build an object file
src/LDAWBICMetropolisSampler.cpp.o:
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/src/LDAWBICMetropolisSampler.cpp.o
.PHONY : src/LDAWBICMetropolisSampler.cpp.o

src/LDAWBICMetropolisSampler.i: src/LDAWBICMetropolisSampler.cpp.i

.PHONY : src/LDAWBICMetropolisSampler.i

# target to preprocess a source file
src/LDAWBICMetropolisSampler.cpp.i:
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/src/LDAWBICMetropolisSampler.cpp.i
.PHONY : src/LDAWBICMetropolisSampler.cpp.i

src/LDAWBICMetropolisSampler.s: src/LDAWBICMetropolisSampler.cpp.s

.PHONY : src/LDAWBICMetropolisSampler.s

# target to generate assembly for a file
src/LDAWBICMetropolisSampler.cpp.s:
	$(MAKE) -f CMakeFiles/LDAWBIC.dir/build.make CMakeFiles/LDAWBIC.dir/src/LDAWBICMetropolisSampler.cpp.s
.PHONY : src/LDAWBICMetropolisSampler.cpp.s

src/OrdinaryGibbsSamplerFromLDA.o: src/OrdinaryGibbsSamplerFromLDA.cpp.o

.PHONY : src/OrdinaryGibbsSamplerFromLDA.o

# target to build an object file
src/OrdinaryGibbsSamplerFromLDA.cpp.o:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/OrdinaryGibbsSamplerFromLDA.cpp.o
.PHONY : src/OrdinaryGibbsSamplerFromLDA.cpp.o

src/OrdinaryGibbsSamplerFromLDA.i: src/OrdinaryGibbsSamplerFromLDA.cpp.i

.PHONY : src/OrdinaryGibbsSamplerFromLDA.i

# target to preprocess a source file
src/OrdinaryGibbsSamplerFromLDA.cpp.i:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/OrdinaryGibbsSamplerFromLDA.cpp.i
.PHONY : src/OrdinaryGibbsSamplerFromLDA.cpp.i

src/OrdinaryGibbsSamplerFromLDA.s: src/OrdinaryGibbsSamplerFromLDA.cpp.s

.PHONY : src/OrdinaryGibbsSamplerFromLDA.s

# target to generate assembly for a file
src/OrdinaryGibbsSamplerFromLDA.cpp.s:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/OrdinaryGibbsSamplerFromLDA.cpp.s
.PHONY : src/OrdinaryGibbsSamplerFromLDA.cpp.s

src/VariationalBayesEstimatorOnLDA.o: src/VariationalBayesEstimatorOnLDA.cpp.o

.PHONY : src/VariationalBayesEstimatorOnLDA.o

# target to build an object file
src/VariationalBayesEstimatorOnLDA.cpp.o:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/VariationalBayesEstimatorOnLDA.cpp.o
.PHONY : src/VariationalBayesEstimatorOnLDA.cpp.o

src/VariationalBayesEstimatorOnLDA.i: src/VariationalBayesEstimatorOnLDA.cpp.i

.PHONY : src/VariationalBayesEstimatorOnLDA.i

# target to preprocess a source file
src/VariationalBayesEstimatorOnLDA.cpp.i:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/VariationalBayesEstimatorOnLDA.cpp.i
.PHONY : src/VariationalBayesEstimatorOnLDA.cpp.i

src/VariationalBayesEstimatorOnLDA.s: src/VariationalBayesEstimatorOnLDA.cpp.s

.PHONY : src/VariationalBayesEstimatorOnLDA.s

# target to generate assembly for a file
src/VariationalBayesEstimatorOnLDA.cpp.s:
	$(MAKE) -f CMakeFiles/LDA.dir/build.make CMakeFiles/LDA.dir/src/VariationalBayesEstimatorOnLDA.cpp.s
.PHONY : src/VariationalBayesEstimatorOnLDA.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... LDA"
	@echo "... ATM"
	@echo "... LDAWBIC"
	@echo "... rebuild_cache"
	@echo "... src/ATM.o"
	@echo "... src/ATM.i"
	@echo "... src/ATM.s"
	@echo "... src/AuthorFileParser.o"
	@echo "... src/AuthorFileParser.i"
	@echo "... src/AuthorFileParser.s"
	@echo "... src/BOWFileParser.o"
	@echo "... src/BOWFileParser.i"
	@echo "... src/BOWFileParser.s"
	@echo "... src/CollapsedGibbsSamplerFromATM.o"
	@echo "... src/CollapsedGibbsSamplerFromATM.i"
	@echo "... src/CollapsedGibbsSamplerFromATM.s"
	@echo "... src/CollapsedGibbsSamplerFromLDA.o"
	@echo "... src/CollapsedGibbsSamplerFromLDA.i"
	@echo "... src/CollapsedGibbsSamplerFromLDA.s"
	@echo "... src/GibbsSamplerFromATM.o"
	@echo "... src/GibbsSamplerFromATM.i"
	@echo "... src/GibbsSamplerFromATM.s"
	@echo "... src/GibbsSamplerFromLDA.o"
	@echo "... src/GibbsSamplerFromLDA.i"
	@echo "... src/GibbsSamplerFromLDA.s"
	@echo "... src/LDA.o"
	@echo "... src/LDA.i"
	@echo "... src/LDA.s"
	@echo "... src/LDAWBIC.o"
	@echo "... src/LDAWBIC.i"
	@echo "... src/LDAWBIC.s"
	@echo "... src/LDAWBICMetropolisSampler.o"
	@echo "... src/LDAWBICMetropolisSampler.i"
	@echo "... src/LDAWBICMetropolisSampler.s"
	@echo "... src/OrdinaryGibbsSamplerFromLDA.o"
	@echo "... src/OrdinaryGibbsSamplerFromLDA.i"
	@echo "... src/OrdinaryGibbsSamplerFromLDA.s"
	@echo "... src/VariationalBayesEstimatorOnLDA.o"
	@echo "... src/VariationalBayesEstimatorOnLDA.i"
	@echo "... src/VariationalBayesEstimatorOnLDA.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

